[package]
name = "wasmedge_quickjs"
version = "0.3.0"
authors = ["csh <458761603@qq.com>", "Michael Yuan <michael@secondstate.io>"]
description = "Create your own JavaScript runtime and extension APIs for WasmEdge."
repository = "https://github.com/second-state/wasmedge-quickjs"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://www.secondstate.io/articles/run-javascript-in-webassembly-with-wasmedge/"
homepage = "https://www.secondstate.io/"
edition = "2018"
exclude = [
    "example_js/*",
    "examples/*",
]

[dependencies]
httpcodec = "0.2.3"
bytecodec = "0.4.15"

argparse = "0.2.2"
image = { version = "0.23.0", default-features = false, features = ["jpeg", "png"] }
imageproc = "0.22.0"
wasmedge_http_req = { version = "0.8.1", optional = true }
wasmedge_wasi_socket = { version = "0.1.0", optional = true }
libc = "0.2"

lazy_static = "1.4"


[features]
default = []
http = ["wasmedge_http_req", "wasmedge_wasi_socket"]
img = []
tensorflow = ["img"]
cjs = []
